name: Laravel CI

on:
  push:
    branches:
      - main
      - porto_dev
  pull_request:
    branches:
      - main
      - porto_dev

jobs:

  frontend:
    name: Astro Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Astro project
        run: npm run astro:build

  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare Laravel environment
        run: |
          cp .env.example .env

      - name: Build Docker image
        run: docker compose build

      - name: Start containers
        run: docker compose up -d

      - name: Install dependencies
        run: |
         docker compose exec -T app composer install \
            --no-interaction \
            --prefer-dist \
            --no-progress            

      - name: Verify Laravel environment
        run: |
         docker compose exec -T app \
          test -f /var/www/.env

      - name: Generate application key
        run: |
         docker compose exec -T app \
          php artisan key:generate

      - name: Run tests
        run: | 
          docker compose exec -T app \
            php artisan test

      - name: Show container logs on failure
        if: failure()
        run: docker compose logs --tail=100

      - name: Stop containers
        if: always()
        run: docker compose down -v
